name: GitHub Auto Deploy To Tencent Cloud
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Tencent Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_HOST_NAME }}
          username: ${{ secrets.TENCENT_HOST_USER }}
          key: ${{ secrets.TENCENT_CLOUD_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ./projects/noppt.github.io/
            git checkout develop
            git pull
            ls -al
            hexo clean
            hexo generate
            cp -r ./public/ /usr/share/nginx/html/blog/
